package br.com.ajudamutua.hardening;
import br.com.ajudamutua.model.*; import br.com.ajudamutua.repository.*; import org.slf4j.*; import org.springframework.beans.factory.ObjectProvider; import org.springframework.beans.factory.annotation.Value; import org.springframework.data.redis.core.StringRedisTemplate; import org.springframework.stereotype.Service;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.*; import java.util.*;
@Service public class LoginAttemptService {private static final Logger log=LoggerFactory.getLogger(LoginAttemptService.class);private final AppUserRepository users;private final LoginSecurityEventRepository events;private final StringRedisTemplate redis;private final String prefix;private final boolean redisEnabled;
 public LoginAttemptService(AppUserRepository u,LoginSecurityEventRepository e,ObjectProvider<StringRedisTemplate> rp,@Value("${app.distributed-security.key-prefix:ajuda-mutua}") String prefix,@Value("${app.distributed-security.redis-enabled:true}") boolean redisEnabled){users=u;events=e;redis=rp.getIfAvailable();this.prefix=prefix;this.redisEnabled=redisEnabled;}
 public void success(String email,String ip){distributedClear(email);users.findByEmailIgnoreCase(email).ifPresent(u->{u.loginSucceeded();users.save(u);event(u,email,"LOGIN_SUCCESS",ip);});}
 public void failure(String email,String ip){if(email==null)return;long failures=distributedFailure(email);var found=users.findByEmailIgnoreCase(email);found.ifPresentOrElse(u->{u.loginFailed();if(failures>=5&&!isLocked(u))u.lockForSeconds(900);users.save(u);event(u,email,u.getLockedUntil()!=null?"LOGIN_LOCKED":"LOGIN_FAILURE",ip);if(u.getLockedUntil()!=null)log.warn("security login lockout userId={}",u.getId());},()->event(null,email,"LOGIN_FAILURE_UNKNOWN",ip));}
 private long distributedFailure(String email){if(!redisEnabled||redis==null)return 0;try{String k=prefix+":loginfail:"+sha(email.toLowerCase());Long n=redis.opsForValue().increment(k);if(n!=null&&n==1)redis.expire(k,Duration.ofMinutes(15));return n==null?0:n;}catch(Exception e){return 0;}}
 private void distributedClear(String email){if(!redisEnabled||redis==null||email==null)return;try{redis.delete(prefix+":loginfail:"+sha(email.toLowerCase()));}catch(Exception ignored){}}
 private boolean isLocked(AppUser u){return u.getLockedUntil()!=null&&u.getLockedUntil().isAfter(Instant.now());}
 private void event(AppUser u,String email,String type,String ip){events.save(new LoginSecurityEvent(UUID.randomUUID(),u==null?null:u.getId(),sha(email==null?"":email.toLowerCase()),type,prefixIp(ip),Instant.now()));}
 private String prefixIp(String ip){if(ip==null)return null;if(ip.contains(":")){var p=ip.split(":");return String.join(":",Arrays.copyOf(p,Math.min(4,p.length)))+"::/64";}var p=ip.split("\\.");return p.length==4?p[0]+"."+p[1]+"."+p[2]+".0/24":null;}
 private String sha(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
