package br.com.ajudamutua.mfa;
import br.com.ajudamutua.crypto.SecretProtector; import br.com.ajudamutua.model.*; import br.com.ajudamutua.repository.AppUserRepository; import br.com.ajudamutua.service.*; import jakarta.servlet.http.HttpSession; import org.springframework.web.bind.annotation.*; import java.util.Map;
@RestController @RequestMapping("/api/v1/mfa") public class MfaController {
 private final CurrentUserService current; private final AppUserRepository users; private final TotpService totp; private final SecretProtector crypto; private final AuditService audit;
 public MfaController(CurrentUserService c,AppUserRepository u,TotpService t,SecretProtector cr,AuditService a){current=c;users=u;totp=t;crypto=cr;audit=a;}
 public record CodeRequest(String code){}
 @PostMapping("/enroll") public Map<String,String> enroll(){AppUser u=current.require(); if(u.getRole()==UserRole.MEMBER)throw new IllegalStateException("MFA obrigatório apenas para perfis privilegiados nesta fase");String secret=totp.newSecret();u.configureMfa(crypto.encrypt(secret),false);users.save(u);audit.append(u.getId(),"MFA_ENROLL_STARTED","AppUser",u.getId(),"{}");return Map.of("secret",secret,"algorithm","TOTP-SHA1","digits","6","period","30");}
 @PostMapping("/confirm") public Map<String,Boolean> confirm(@RequestBody CodeRequest in,HttpSession session){AppUser u=current.require();String enc=u.getMfaSecretEnc();if(enc==null)throw new IllegalStateException("MFA não iniciado");if(!totp.verify(crypto.decrypt(enc),in.code()))throw new IllegalArgumentException("Código MFA inválido");u.configureMfa(enc,true);users.save(u);session.setAttribute("MFA_VERIFIED",Boolean.TRUE);audit.append(u.getId(),"MFA_ENABLED","AppUser",u.getId(),"{}");return Map.of("enabled",true);}
 @PostMapping("/verify") public Map<String,Boolean> verify(@RequestBody CodeRequest in,HttpSession session){AppUser u=current.require();if(!u.isMfaEnabled())throw new IllegalStateException("MFA não habilitado");if(!totp.verify(crypto.decrypt(u.getMfaSecretEnc()),in.code()))throw new IllegalArgumentException("Código MFA inválido");session.setAttribute("MFA_VERIFIED",Boolean.TRUE);audit.append(u.getId(),"MFA_SESSION_VERIFIED","AppUser",u.getId(),"{}");return Map.of("verified",true);}
}
