package br.com.ajudamutua.crypto;
import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.stereotype.Component;
import software.amazon.awssdk.core.SdkBytes; import software.amazon.awssdk.services.kms.KmsClient; import software.amazon.awssdk.services.kms.model.*;
import javax.crypto.Cipher; import javax.crypto.spec.GCMParameterSpec; import javax.crypto.spec.SecretKeySpec; import java.nio.charset.StandardCharsets; import java.security.SecureRandom; import java.util.Base64;
@Component @ConditionalOnProperty(name="app.kms.provider",havingValue="aws-kms")
public class AwsKmsSecretProtector implements SecretProtector {
 private final KmsClient kms; private final String keyId; private final SecureRandom random=new SecureRandom();
 public AwsKmsSecretProtector(@Value("${app.kms.aws-key-id:}") String keyId){if(keyId==null||keyId.isBlank())throw new IllegalStateException("AWS_KMS_KEY_ID obrigatório quando KMS_PROVIDER=aws-kms");this.keyId=keyId;this.kms=KmsClient.create();}
 public String encrypt(String plaintext){if(plaintext==null)return null;try{GenerateDataKeyResponse dk=kms.generateDataKey(GenerateDataKeyRequest.builder().keyId(keyId).keySpec(DataKeySpec.AES_256).build());byte[] dataKey=dk.plaintext().asByteArray();byte[] iv=new byte[12];random.nextBytes(iv);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(dataKey,"AES"),new GCMParameterSpec(128,iv));byte[] out=c.doFinal(plaintext.getBytes(StandardCharsets.UTF_8));java.util.Arrays.fill(dataKey,(byte)0);return "kms1:"+keyId+":"+Base64.getEncoder().encodeToString(dk.ciphertextBlob().asByteArray())+":"+Base64.getEncoder().encodeToString(iv)+":"+Base64.getEncoder().encodeToString(out);}catch(Exception e){throw new IllegalStateException("Falha ao criptografar via AWS KMS",e);}}
 public String decrypt(String ciphertext){if(ciphertext==null)return null;try{String[] p=ciphertext.split(":",5);if(p.length!=5||!"kms1".equals(p[0]))throw new IllegalArgumentException("Ciphertext KMS inválido");DecryptResponse dr=kms.decrypt(DecryptRequest.builder().ciphertextBlob(SdkBytes.fromByteArray(Base64.getDecoder().decode(p[2]))).build());byte[] dataKey=dr.plaintext().asByteArray();Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,new SecretKeySpec(dataKey,"AES"),new GCMParameterSpec(128,Base64.getDecoder().decode(p[3])));byte[] out=c.doFinal(Base64.getDecoder().decode(p[4]));java.util.Arrays.fill(dataKey,(byte)0);return new String(out,StandardCharsets.UTF_8);}catch(Exception e){throw new IllegalStateException("Falha ao descriptografar via AWS KMS",e);}}
 public String keyId(){return keyId;}
}
