package br.com.ajudamutua.service;
import br.com.ajudamutua.dto.ApiDtos; import org.springframework.beans.factory.annotation.Value; import br.com.ajudamutua.model.*; import br.com.ajudamutua.repository.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile; import org.springframework.core.io.Resource; import java.time.Instant; import java.util.*;
@Service
public class CommunityService {
 private final MemberRepository members; private final AidRequestRepository aids; private final LedgerEntryRepository ledgerRepo; private final LedgerService ledger; private final AppUserRepository users; private final AidApprovalRepository approvals; private final AidAnalysisRepository analyses; private final AidDocumentRepository documents; private final FraudScreeningRepository fraud; private final PasswordEncoder encoder; private final CurrentUserService current; private final AuditService audit; private final AidPolicyService policy; private final DocumentStorageService storage; @Value("${app.privacy.document-retention-days:365}") private long documentRetentionDays;
 public CommunityService(MemberRepository members,AidRequestRepository aids,LedgerEntryRepository ledgerRepo,LedgerService ledger,AppUserRepository users,AidApprovalRepository approvals,AidAnalysisRepository analyses,AidDocumentRepository documents,FraudScreeningRepository fraud,PasswordEncoder encoder,CurrentUserService current,AuditService audit,AidPolicyService policy,DocumentStorageService storage){this.members=members;this.aids=aids;this.ledgerRepo=ledgerRepo;this.ledger=ledger;this.users=users;this.approvals=approvals;this.analyses=analyses;this.documents=documents;this.fraud=fraud;this.encoder=encoder;this.current=current;this.audit=audit;this.policy=policy;this.storage=storage;}
 @Transactional public AppUser register(ApiDtos.RegisterMember in){String email=in.email().trim().toLowerCase(); if(users.findByEmailIgnoreCase(email).isPresent()) throw new IllegalStateException("E-mail já cadastrado"); Member m=members.save(new Member(UUID.randomUUID(),in.name().trim(),email,MemberStatus.ACTIVE,Instant.now())); AppUser u=users.save(new AppUser(UUID.randomUUID(),email,encoder.encode(in.password()),UserRole.MEMBER,m.getId(),true,Instant.now())); audit.append(u.getId(),"MEMBER_REGISTERED","Member",m.getId(),"{}"); return u;}
 @PreAuthorize("hasRole('ADMIN')") public Member createMember(ApiDtos.CreateMember in){return members.save(new Member(UUID.randomUUID(),in.name().trim(),in.email().trim().toLowerCase(),MemberStatus.ACTIVE,Instant.now()));}
 @Transactional @PreAuthorize("hasAnyRole('MEMBER','ADMIN')") public LedgerEntry contribute(ApiDtos.Contribution in){AppUser u=current.require(); if(u.getRole()==UserRole.MEMBER&&!Objects.equals(u.getMemberId(),in.memberId())) throw new IllegalStateException("Membro só pode contribuir em seu próprio nome"); Member m=requireActive(in.memberId()); LedgerEntry e=ledger.append(LedgerType.CONTRIBUTION,in.amount(),m.getId(),null,"Contribuição voluntária"); audit.append(u.getId(),"CONTRIBUTION_RECORDED","LedgerEntry",e.getId(),"{\"amount\":\""+in.amount()+"\"}"); return e;}
 @Transactional @PreAuthorize("hasAnyRole('MEMBER','ADMIN')") public AidRequest requestAid(ApiDtos.CreateAid in){AppUser u=current.require(); if(u.getRole()==UserRole.MEMBER&&!Objects.equals(u.getMemberId(),in.memberId())) throw new IllegalStateException("Membro só pode criar pedido para si"); requireActive(in.memberId()); if(aids.existsByMemberIdAndStatusIn(in.memberId(),List.of(AidStatus.PENDING,AidStatus.APPROVED))) throw new IllegalStateException("Já existe um pedido pendente ou aprovado para este membro"); AidRequest a=aids.save(new AidRequest(UUID.randomUUID(),in.memberId(),in.amount(),in.category(),in.reason().trim(),in.emergency(),AidStatus.PENDING,Instant.now())); audit.append(u.getId(),"AID_REQUEST_CREATED","AidRequest",a.getId(),"{\"amount\":\""+in.amount()+"\",\"category\":\""+in.category()+"\"}"); return a;}
 @Transactional @PreAuthorize("hasAnyRole('MEMBER','ADMIN')") public AidDocument addDocument(UUID id,String documentType,MultipartFile file){AppUser u=current.require(); AidRequest a=requireAid(id); if(a.getStatus()!=AidStatus.PENDING) throw new IllegalStateException("Documentos só podem ser adicionados enquanto o pedido está pendente"); if(u.getRole()==UserRole.MEMBER&&!Objects.equals(u.getMemberId(),a.getMemberId())) throw new IllegalStateException("Membro só pode anexar documento ao próprio pedido"); if(documentType==null||documentType.isBlank()||documentType.length()>60) throw new IllegalArgumentException("Tipo de documento inválido"); var stored=storage.store(file); String original=sanitizeFileName(Objects.requireNonNullElse(file.getOriginalFilename(),"documento")); AidDocument d=new AidDocument(UUID.randomUUID(),id,documentType.trim().toUpperCase(),original,stored.key(),stored.contentType(),stored.size(),stored.sha256(),u.getId(),Instant.now()); d.setRetentionUntil(Instant.now().plusSeconds(Math.max(30,documentRetentionDays)*86400)); d=documents.save(d); audit.append(u.getId(),"AID_DOCUMENT_REGISTERED","AidRequest",id,"{\"documentType\":\""+safe(documentType)+"\",\"sha256\":\""+stored.sha256()+"\"}"); return d;}
 @PreAuthorize("hasAnyRole('MEMBER','ANALYST','APPROVER','ADMIN','AUDITOR')") public DocumentDownload documentContent(UUID documentId){AidDocument d=documents.findById(documentId).orElseThrow(()->new IllegalArgumentException("Documento não encontrado")); AidRequest a=requireAid(d.getAidRequestId()); AppUser u=current.require(); if(u.getRole()==UserRole.MEMBER&&!Objects.equals(u.getMemberId(),a.getMemberId())) throw new IllegalStateException("Acesso negado"); return new DocumentDownload(storage.load(d.getStorageKey()),d.getFileName(),d.getContentType());}
 @Transactional @PreAuthorize("hasRole('ANALYST')") public AidAnalysis analyze(UUID id,String opinion){AppUser u=current.require(); AidRequest a=requireAid(id); if(a.getStatus()!=AidStatus.PENDING) throw new IllegalStateException("Pedido não está pendente"); AidAnalysis x=analyses.save(new AidAnalysis(UUID.randomUUID(),id,u.getId(),opinion.trim(),Instant.now())); audit.append(u.getId(),"AID_ANALYZED","AidRequest",id,"{}"); return x;}
 @Transactional @PreAuthorize("hasRole('ANALYST')") public FraudScreening screenFraud(UUID id,ApiDtos.FraudReview in){AppUser u=current.require(); AidRequest a=requireAid(id); if(a.getStatus()!=AidStatus.PENDING) throw new IllegalStateException("Triagem só pode ser registrada para pedido pendente"); if(in.status()==FraudScreeningStatus.PENDING) throw new IllegalArgumentException("Analista deve concluir a triagem como CLEARED, REVIEW_REQUIRED ou BLOCKED"); if(in.status()==FraudScreeningStatus.CLEARED && in.riskScore()>=80) throw new IllegalArgumentException("Risco >= 80 não pode ser marcado como CLEARED"); if(fraud.findByAidRequestId(id).isPresent()) throw new IllegalStateException("Triagem antifraude já registrada; mantenha histórico imutável"); FraudScreening f=fraud.save(new FraudScreening(UUID.randomUUID(),id,u.getId(),in.status(),in.riskScore(),safe(in.flags()),safe(in.note()),Instant.now())); audit.append(u.getId(),"FRAUD_SCREENING_COMPLETED","AidRequest",id,"{\"status\":\""+in.status()+"\",\"riskScore\":"+in.riskScore()+"}"); return f;}
 @PreAuthorize("hasAnyRole('MEMBER','ANALYST','APPROVER','ADMIN','AUDITOR')") public ApiDtos.EligibilityResult eligibility(UUID id){AidRequest a=requireAid(id); AppUser u=current.require(); if(u.getRole()==UserRole.MEMBER&&!Objects.equals(u.getMemberId(),a.getMemberId())) throw new IllegalStateException("Membro só pode consultar elegibilidade do próprio pedido"); return policy.evaluate(a);}
 @Transactional @PreAuthorize("hasRole('APPROVER')") public ApiDtos.ApprovalResult approve(UUID id,String note){AppUser u=current.require(); AidRequest a=requireAid(id); if(a.getStatus()==AidStatus.REJECTED||a.getStatus()==AidStatus.PAID) throw new IllegalStateException("Pedido não pode ser aprovado neste estado"); ApiDtos.EligibilityResult eligibility=policy.evaluate(a); if(!eligibility.eligible()) throw new IllegalStateException("Pedido inelegível: "+String.join("; ",eligibility.blockers())); if(approvals.existsByAidRequestIdAndApproverUserId(id,u.getId())) throw new IllegalStateException("Este usuário já aprovou o pedido"); approvals.save(new AidApproval(UUID.randomUUID(),id,u.getId(),note.trim(),Instant.now())); long count=approvals.countByAidRequestId(id); if(count>=2 && a.getStatus()==AidStatus.PENDING) a.approve("Dupla aprovação concluída após elegibilidade objetiva"); audit.append(u.getId(),"AID_APPROVED","AidRequest",id,"{\"approvalCount\":"+count+"}"); return new ApiDtos.ApprovalResult(id,2,count,a.getStatus().name());}
 @Transactional @PreAuthorize("hasRole('APPROVER')") public AidRequest reject(UUID id,String note){AppUser u=current.require(); AidRequest a=requireAid(id); if(a.getStatus()==AidStatus.PAID) throw new IllegalStateException("Pedido pago não pode ser rejeitado"); a.reject(note); audit.append(u.getId(),"AID_REJECTED","AidRequest",id,"{}"); return a;}
 @PreAuthorize("hasAnyRole('APPROVER','ADMIN','AUDITOR')") public List<LedgerEntry> ledger(){return ledgerRepo.findAll(org.springframework.data.domain.Sort.by("createdAt").descending());}
 @PreAuthorize("hasAnyRole('ANALYST','APPROVER','ADMIN','AUDITOR')") public List<AidRequest> aidRequests(){return aids.findAll(org.springframework.data.domain.Sort.by("createdAt").descending());}
 @PreAuthorize("hasRole('MEMBER')") public List<AidRequest> myAidRequests(){AppUser u=current.require(); return aids.findByMemberIdOrderByCreatedAtDesc(u.getMemberId());}
 @PreAuthorize("hasAnyRole('ANALYST','APPROVER','ADMIN','AUDITOR','MEMBER')") public List<AidDocument> documents(UUID id){AidRequest a=requireAid(id); AppUser u=current.require(); if(u.getRole()==UserRole.MEMBER&&!Objects.equals(u.getMemberId(),a.getMemberId())) throw new IllegalStateException("Acesso negado"); return documents.findByAidRequestId(id);}
 public ApiDtos.Transparency transparency(){long active=members.findAll().stream().filter(m->m.getStatus()==MemberStatus.ACTIVE).count(); long paid=aids.findAll().stream().filter(a->a.getStatus()==AidStatus.PAID).count(); return new ApiDtos.Transparency(ledger.balance(),active,aids.count(),paid);}
 public List<ApiDtos.PublicLedgerEntry> publicLedger(){return ledgerRepo.findAll(org.springframework.data.domain.Sort.by("createdAt").descending()).stream().map(e->new ApiDtos.PublicLedgerEntry(e.getType().name(),e.getAmount(),e.getDescription(),e.getCreatedAt(),e.getEntryHash())).toList();}
 public List<ApiDtos.CategoryPolicy> categoryPolicies(){return Arrays.stream(AidCategory.values()).map(c->{var p=policy.policy(c);return new ApiDtos.CategoryPolicy(c,p.waitingDays(),p.cooldownDays(),p.maxAmount(),p.documentRequired());}).toList();}
 @PreAuthorize("hasAnyRole('AUDITOR','ADMIN')") public List<AuditEvent> auditEvents(){return audit.all();}
 public record DocumentDownload(Resource resource,String fileName,String contentType){}
 private Member requireActive(UUID id){Member m=members.findById(id).orElseThrow(()->new IllegalArgumentException("Membro não encontrado")); if(m.getStatus()!=MemberStatus.ACTIVE) throw new IllegalStateException("Membro não está ativo"); return m;}
 private AidRequest requireAid(UUID id){return aids.findById(id).orElseThrow(()->new IllegalArgumentException("Pedido não encontrado"));}
 private String sanitizeFileName(String s){return s.replace("/","_").replace("\\","_").trim();}
 private String safe(String s){return s==null?"":s.replace("\\","_").replace("\"","'").replace("\n"," ").replace("\r"," ");}
}
