package br.com.ajudamutua.privacy;
import br.com.ajudamutua.crypto.SecretProtector; import br.com.ajudamutua.model.*; import br.com.ajudamutua.repository.*; import br.com.ajudamutua.service.*; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.util.*;
@Service public class DsarService {
 private final DsarRequestRepository dsars; private final MemberRepository members; private final MemberPrivateDataRepository privateData; private final ConsentRecordRepository consents; private final AidRequestRepository aids; private final LedgerEntryRepository ledger; private final CurrentUserService current; private final SecretProtector crypto; private final AuditService audit; private final ObjectMapper mapper;
 public DsarService(DsarRequestRepository d,MemberRepository m,MemberPrivateDataRepository p,ConsentRecordRepository c,AidRequestRepository a,LedgerEntryRepository l,CurrentUserService cu,SecretProtector cr,AuditService au,ObjectMapper om){dsars=d;members=m;privateData=p;consents=c;aids=a;ledger=l;current=cu;crypto=cr;audit=au;mapper=om;}
 @Transactional @PreAuthorize("hasRole('MEMBER')") public DsarRequest request(DsarRequestType type){AppUser u=current.require();DsarRequest r=dsars.save(new DsarRequest(UUID.randomUUID(),u.getMemberId(),type));audit.append(u.getId(),"DSAR_REQUESTED","DsarRequest",r.getId(),"{\"type\":\""+type+"\"}");return r;}
 @PreAuthorize("hasRole('MEMBER')") public List<DsarRequest> mine(){return dsars.findByMemberIdOrderByRequestedAtDesc(current.require().getMemberId());}
 @Transactional(readOnly=true) @PreAuthorize("hasAnyRole('MEMBER','ADMIN','AUDITOR')") public Map<String,Object> export(UUID memberId){AppUser u=current.require();if(u.getRole()==UserRole.MEMBER&&!Objects.equals(u.getMemberId(),memberId))throw new IllegalStateException("Acesso negado");Member m=members.findById(memberId).orElseThrow();Map<String,Object> out=new LinkedHashMap<>();out.put("member",Map.of("id",m.getId(),"name",m.getName(),"email",m.getEmail(),"status",m.getStatus(),"joinedAt",m.getJoinedAt()));privateData.findById(memberId).ifPresent(p->out.put("privateData",Map.of("cpf",crypto.decrypt(p.getCpfCiphertext()),"address",crypto.decrypt(p.getAddressCiphertext()),"updatedAt",p.getUpdatedAt())));out.put("consents",consents.findByMemberIdOrderByAcceptedAtDesc(memberId));out.put("aidRequests",aids.findByMemberIdOrderByCreatedAtDesc(memberId));out.put("ledger",ledger.findByMemberIdOrderByCreatedAtDesc(memberId));audit.append(u.getId(),"DSAR_EXPORT_GENERATED","Member",memberId,"{}");return out;}
 @Transactional @PreAuthorize("hasAnyRole('ADMIN','AUDITOR')") public DsarRequest complete(UUID id,String notes){AppUser actor=current.require();DsarRequest r=dsars.findById(id).orElseThrow();String hash=null;if(r.getRequestType()==DsarRequestType.ACCESS_EXPORT){try{hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(mapper.writeValueAsString(export(r.getMemberId())).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}r.complete(actor.getId(),notes,hash);audit.append(actor.getId(),"DSAR_COMPLETED","DsarRequest",id,"{}");return r;}
}
