package br.com.ajudamutua.privacy;
import br.com.ajudamutua.model.*; import br.com.ajudamutua.crypto.SecretProtector; import br.com.ajudamutua.repository.*; import br.com.ajudamutua.service.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Instant; import java.util.*;
@Service public class PrivacyService {
 private final MemberRepository members; private final SecretProtector crypto; private final PiiAccessPolicy piiPolicy; private final MemberPrivateDataRepository privateData; private final KycVerificationRepository kyc; private final ConsentRecordRepository consents; private final CurrentUserService current; private final AuditService audit;
 public PrivacyService(MemberRepository m,MemberPrivateDataRepository p,KycVerificationRepository k,ConsentRecordRepository c,CurrentUserService cu,AuditService a,SecretProtector cr,PiiAccessPolicy pp){members=m;privateData=p;kyc=k;consents=c;current=cu;audit=a;crypto=cr;piiPolicy=pp;}
 @Transactional @PreAuthorize("hasRole('MEMBER')") public MemberPrivateData savePrivateData(String cpf,String address){AppUser u=current.require();String digits=cpf==null?"":cpf.replaceAll("\\D","");if(digits.length()!=11)throw new IllegalArgumentException("CPF deve conter 11 dígitos");String hash=sha256(digits);String last4=digits.substring(7);String redacted=redactAddress(address);MemberPrivateData d=new MemberPrivateData(u.getMemberId(),hash,last4,redacted,Instant.now()); d.protect(crypto.encrypt(digits),crypto.encrypt(address==null?"":address.trim()),crypto.keyId()); d=privateData.save(d);audit.append(u.getId(),"PRIVATE_DATA_UPDATED","Member",u.getMemberId(),"{\"cpf\":\"***"+last4+"\"}");return d;}
 @Transactional @PreAuthorize("hasRole('MEMBER')") public ConsentRecord consent(ConsentType type,String version,boolean accepted,String ip){AppUser u=current.require();if(version==null||version.isBlank())throw new IllegalArgumentException("Versão obrigatória");ConsentRecord r=consents.save(new ConsentRecord(UUID.randomUUID(),u.getMemberId(),type,version.trim(),accepted,normalizeIp(ip),Instant.now()));audit.append(u.getId(),"CONSENT_RECORDED","Member",u.getMemberId(),"{\"type\":\""+type+"\",\"version\":\""+version.replace("\"","'")+"\",\"accepted\":"+accepted+"}");return r;}
 @Transactional @PreAuthorize("hasRole('MEMBER')") public KycVerification submitKyc(){AppUser u=current.require();Member m=members.findById(u.getMemberId()).orElseThrow();if(privateData.findById(m.getId()).isEmpty())throw new IllegalStateException("Dados privados devem ser cadastrados antes do KYC");m.setKycStatus(KycStatus.PENDING);KycVerification v=kyc.save(new KycVerification(UUID.randomUUID(),m.getId(),KycStatus.PENDING,"SANDBOX",null,null,null,Instant.now()));audit.append(u.getId(),"KYC_SUBMITTED","Member",m.getId(),"{}");return v;}
 @Transactional @PreAuthorize("hasAnyRole('ANALYST','ADMIN')") public KycVerification review(UUID memberId,KycStatus status,String reason){if(status!=KycStatus.VERIFIED&&status!=KycStatus.REJECTED)throw new IllegalArgumentException("Status de revisão inválido");AppUser actor=current.require();Member m=members.findById(memberId).orElseThrow(()->new IllegalArgumentException("Membro não encontrado"));m.setKycStatus(status);KycVerification v=kyc.save(new KycVerification(UUID.randomUUID(),memberId,status,"SANDBOX",null,actor.getId(),status==KycStatus.REJECTED?reason:null,Instant.now()));audit.append(actor.getId(),"KYC_REVIEWED","Member",memberId,"{\"status\":\""+status+"\"}");return v;}
 @PreAuthorize("hasAnyRole('MEMBER','ANALYST','ADMIN','AUDITOR')") public List<ConsentRecord> consents(UUID memberId){AppUser u=current.require();if(u.getRole()==UserRole.MEMBER&&!Objects.equals(u.getMemberId(),memberId))throw new IllegalStateException("Acesso negado");return consents.findByMemberIdOrderByAcceptedAtDesc(memberId);}
 @PreAuthorize("hasAnyRole('MEMBER','ANALYST','ADMIN','AUDITOR')") public PiiView privateData(UUID memberId,String purpose){piiPolicy.require(memberId,purpose);MemberPrivateData d=privateData.findById(memberId).orElseThrow(()->new IllegalArgumentException("Dados privados não encontrados"));AppUser actor=current.require();audit.append(actor.getId(),"PII_ACCESSED","Member",memberId,"{\"purpose\":\""+(purpose==null?"SELF":purpose.replace("\"","'"))+"\"}");return new PiiView(memberId,crypto.decrypt(d.getCpfCiphertext()),crypto.decrypt(d.getAddressCiphertext()),d.getUpdatedAt());}
 public record PiiView(UUID memberId,String cpf,String address,Instant updatedAt){}
 private String normalizeIp(String ip){if(ip==null||ip.isBlank())return null;if(ip.contains(":")){String[] p=ip.split(":");return String.join(":",Arrays.copyOf(p,Math.min(4,p.length)))+"::/64";}String[] p=ip.split("\\.");return p.length==4?p[0]+"."+p[1]+"."+p[2]+".0/24":null;}
 private String redactAddress(String a){if(a==null||a.isBlank())return null;String s=a.trim().replaceAll("\\d","*");return s.length()>255?s.substring(0,255):s;}
 private String sha256(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
