package br.com.ajudamutua.recovery;
import br.com.ajudamutua.model.AppUser; import br.com.ajudamutua.repository.AppUserRepository; import br.com.ajudamutua.service.*;
import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*;
@Service public class AccountRecoveryService {
 private final AccountRecoveryRequestRepository requests; private final AccountRecoveryApprovalRepository approvals; private final AppUserRepository users; private final CurrentUserService current; private final AuditService audit;
 public AccountRecoveryService(AccountRecoveryRequestRepository r,AccountRecoveryApprovalRepository a,AppUserRepository u,CurrentUserService c,AuditService au){requests=r;approvals=a;users=u;current=c;audit=au;}
 @Transactional @PreAuthorize("hasRole('ADMIN')") public AccountRecoveryRequest create(UUID targetUserId,String reason){if(reason==null||reason.isBlank())throw new IllegalArgumentException("Motivo obrigatório");AppUser actor=current.require();AppUser target=users.findById(targetUserId).orElseThrow();if(actor.getId().equals(target.getId()))throw new IllegalStateException("Auto-recuperação administrativa não é permitida");Instant now=Instant.now();var r=requests.save(new AccountRecoveryRequest(UUID.randomUUID(),targetUserId,actor.getId(),reason,now,now.plus(Duration.ofHours(1))));audit.append(actor.getId(),"ACCOUNT_RECOVERY_REQUESTED","AppUser",targetUserId,"{\"requestId\":\""+r.getId()+"\"}");return r;}
 @Transactional @PreAuthorize("hasRole('ADMIN')") public AccountRecoveryRequest approve(UUID requestId){AppUser actor=current.require();AccountRecoveryRequest r=requests.findById(requestId).orElseThrow();if(Instant.now().isAfter(r.getExpiresAt())){r.expire();throw new IllegalStateException("Solicitação expirada");}if(r.getRequestedByUserId().equals(actor.getId()))throw new IllegalStateException("Solicitante não pode aprovar a própria recuperação");if(approvals.existsByRecoveryRequestIdAndApproverUserId(requestId,actor.getId()))return r;approvals.save(new AccountRecoveryApproval(UUID.randomUUID(),requestId,actor.getId(),Instant.now()));long count=approvals.countByRecoveryRequestId(requestId);if(count>=2&&r.getStatus()==RecoveryStatus.PENDING)r.markApproved();audit.append(actor.getId(),"ACCOUNT_RECOVERY_APPROVED","AccountRecoveryRequest",requestId,"{\"approvalCount\":"+count+"}");return r;}
 @Transactional @PreAuthorize("hasRole('ADMIN')") public AccountRecoveryRequest execute(UUID requestId){AppUser actor=current.require();AccountRecoveryRequest r=requests.findById(requestId).orElseThrow();if(r.getStatus()!=RecoveryStatus.APPROVED||approvals.countByRecoveryRequestId(requestId)<2)throw new IllegalStateException("Duas aprovações administrativas distintas são obrigatórias");if(approvals.existsByRecoveryRequestIdAndApproverUserId(requestId,actor.getId()))throw new IllegalStateException("Executor não pode ser um dos aprovadores");AppUser target=users.findById(r.getTargetUserId()).orElseThrow();target.resetMfa();target.unlock();users.save(target);r.markExecuted();audit.append(actor.getId(),"ACCOUNT_RECOVERY_EXECUTED","AppUser",target.getId(),"{\"requestId\":\""+requestId+"\"}");return r;}
 @PreAuthorize("hasAnyRole('ADMIN','AUDITOR')") public List<AccountRecoveryRequest> pending(){return requests.findByStatusOrderByCreatedAtDesc(RecoveryStatus.PENDING);}
}
